// <auto-generated />
using DemoMVC.Models.Concerti;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoMVC.Models.Migrations
{
    [DbContext(typeof(BigliettiContext))]
    [Migration("20220228094022_PrimaMigrazione")]
    partial class PrimaMigrazione
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoMVC.Models.Concerti.BigliettoConcerto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artista")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("bit");

                    b.Property<int>("Prezzo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Biglietti");
                });
#pragma warning restore 612, 618
        }
    }
}
